name: Discord Notification on Push to Master

on:
  push:
    branches: [ master ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            🚀 **New Push to Master**
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref }}
            **Author:** ${{ github.actor }}
            **Commit:** ${{ github.event.head_commit.url }}
            **Message:** ${{ github.event.head_commit.message }}
