name: Discord Notification on Push to Master

on:
  push:
    branches: [ master ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: appleboy/discord-action@v0.0.3
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed: true
          color: "3066993"
          author_name: "GitHub Bot"
          author_url: "https://github.com/${{ github.repository }}"
          author_icon: "https://github.com/github.png"
          title: "🚀 New Push to Master"
          url: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref }}
            **Author:** ${{ github.actor }}
            **Message:** ${{ github.event.head_commit.message }}
          timestamp: true
