name: Discord Notification on Push to Master

on:
  push:
    branches: [ master ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send Discord notification
        uses: appleboy/discord-action@v0.0.3
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🚀 **New Push to Master**
            > **Repository:** ${{ github.repository }}
            > **Branch:** ${{ github.ref }}
            > **Author:** ${{ github.actor }}
            > **Commit:** [View](${{ github.event.head_commit.url }})
            > **Message:** ${{ github.event.head_commit.message }}
          avatar: "https://github.com/github.png"
          username: "GitHub Bot"
